export const coffees = [
  {
    image: "/assets/vanilla-latte.png",
    name: "Vanilla Latte",
    rating: 4.8,
    price: 21,
    description:"",
  },
  {
    image: "/assets/espresso.png",
    name: "Espresso",
    rating: 4.8,
    price: 12,
    description:"",
  },
  {
    image: "/assets/hazelnut-latte.png",
    name: "Hazelnut Latte",
    rating: 4.8,
    price: 23,
    description:"",
  },
  {
    image: "/assets/sandwich.png",
    name: "Sandwich",
    rating: 4.8,
    price: 12,
    description:"bread with meat and vegetables",
  },
  {
    image:"/assets/hot-milk.png",
    name: "Hot Milk",
    rating: 4.8,
    price: 12,
    description:"Hot Milk with less sugar",
  },
  {
    image: "/assets/coffe-icecream.png",
    name: "Coffe Ice Cream",
    rating: 4.8,
    price: 23,
    description:"Coffe with ice cream vanilla",
  },
  {
    image: "/assets/cappuccino.png",
    name: "Cappuccino",
    rating: 4.8,
    price: 12,
    description:"Hot Cappucino",
  },
  {
    image: "/assets/moccacinno.png",
    name: "Moccacinno",
    rating: 4.8,
    price: 12,
    description:"Hot Moccacino",
  },
  {
    image: "/assets/waffle-icecream.png",
    name: "Waffle Ice Cream",
    rating: 4.8,
    price: 23,
    description:"Wafle with Ice cream",
  },
];
